### PR TITLE
Formatting with Black and linting with Flake8

### PR DESCRIPTION
**Pull request by gtfierro**
Borrowing the implementation from Brickschema/Brick. Should work fine! Make sure to `pre-commit install` in the repo before using

### CODE REVIEW

**Comment by xyzisinus** [comment]
> pre-commit install

Thanks!  I was wondering how I can test-use the package.

**Comment by gtfierro** [comment]
`pre-commit` just handles running flake8/black before the commit is admitted to staging. Let me know if you're trying to accomplish something else. The repo is using [Poetry](https://python-poetry.org/docs/) for development

**Comment by xyzisinus** [comment]
> `pre-commit` just handles running flake8/black before the commit is admitted to staging. Let me know if you're trying to accomplish something else. The repo is using [Poetry](https://python-poetry.org/docs/) for development

I knew I commented at a wrong place but can't remove it :( I'll read about poetry.

**Comment by gtfierro** [comment]
I'll push some development instructions in a moment that might help

**Pull request merged**
